services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - C:\data\db\mongo:/data/db

  blazorapp:
    build:
      context: .
      dockerfile: AiPeopleFinder/Dockerfile
    container_name: blazorapp
    ports:
      - "8081:80"
    depends_on:
      - mongodb
    environment:
      MongoDB__ConnectionString: "mongodb://admin:admin@mongodb:27017/AiPeopleFinder?authSource=admin"
      ASPNETCORE_URLS: "http://+:80" 